[package]
name = "cards_ui"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]

[dependencies]
conrod = "0.37.*"
find_folder = "*"
piston_window = "*"
[dependencies.cards]
git = "https://github.com/th4t/cards-rs.git"
